Frontend/src/components/layout/Navbar.tsx, Frontend/src/layouts/Layout.tsx
네비게이션 바
https://github.com/user-attachments/assets/b6fde7d4-0933-4eab-943f-5dd1c5829d30
=> [Feature] 네비게이션 바 구현

Frontend/src/components/layout/Navbar.tsx
=> [Fix] Navbar 라우팅 /live -> /live

Frontend/src/components/common/Badges/CategoryBadge.tsx, Frontend/src/components/common/Buttons/FollowButton.tsx, Frontend/src/components/common/LiveInfo/StreamerInfo.tsx, Frontend/src/components/common/LiveInfo/index.tsx, Frontend/src/components/common/VideoPlayer/index.tsx, Frontend/src/components/layout/Navbar.tsx, Frontend/src/layouts/Layout.tsx, Frontend/src/pages/LivePage/index.tsx, Frontend/src/pages/LivesPage/index.tsx, Frontend/src/routes/index.tsx, Frontend/src/styles/index.css
채널페이지의 UI 구현
* 재생 버튼 
* 볼륨 조절 
* 화질 조절 버튼과 모달
* 극장모드
* 전체화면
* Follow 버튼과 Category 뱃지를 컴포넌트로 분리
https://github.com/user-attachments/assets/62d39768-8a35-47b8-9234-d1ed8da21d9a
=> [Feature] 채널 페이지 UI 구현

Backend/.eslintrc.js, Backend/.prettierrc, Backend/package-lock.json, Backend/package.json
=> [Feature] 백엔드 초기 설정 추가

Backend/package-lock.json, Backend/package.json, Backend/src/app.module.ts, Backend/src/auth/auth.controller.spec.ts, Backend/src/auth/auth.controller.ts, Backend/src/auth/auth.module.ts, Backend/src/auth/auth.service.spec.ts, Backend/src/auth/auth.service.ts, Backend/src/categories/categories.controller.spec.ts, Backend/src/categories/categories.controller.ts, Backend/src/categories/categories.module.ts, Backend/src/categories/categories.service.spec.ts, Backend/src/categories/categories.service.ts, Backend/src/main.ts, Backend/src/streaming/streaming.controller.spec.ts, Backend/src/streaming/streaming.controller.ts, Backend/src/streaming/streaming.module.ts, Backend/src/streaming/streaming.service.spec.ts, Backend/src/streaming/streaming.service.ts, Backend/src/users/users.controller.spec.ts, Backend/src/users/users.controller.ts, Backend/src/users/users.module.ts, Backend/src/users/users.service.spec.ts, Backend/src/users/users.service.ts, Backend/src/videos/videos.controller.spec.ts, Backend/src/videos/videos.controller.ts, Backend/src/videos/videos.module.ts, Backend/src/videos/videos.service.spec.ts, Backend/src/videos/videos.service.ts
기본 모듈 생성 
- Auth Module: OAuth 인증 관리
- Users Module: 사용자 관리
- Categories Module: 카테고리 관리
- Streaming Module: 스트리밍 관리
- Videos Module: 비디오 관리
환경 변수 세팅
-  환경변수(`.env`) 관리를 위해서 `@nestjs/config` 설치
-  nestJS는 `dotenv` 보다  `@nestjs/config` 권장한다고 합니다.
- 참고 : https://far-woodwind-e60.notion.site/9810b15264954ed1b5f64d208483230d?pvs=4
=> [Feature] 기본 모듈 생성 및 환경 변수 세팅

Frontend/src/components/chat/ChatHeader.tsx, Frontend/src/components/chat/ChatInput.tsx, Frontend/src/components/chat/ChatMessage.tsx, Frontend/src/components/chat/ChatWindow.tsx, Frontend/src/components/chat/constants.ts, Frontend/src/components/chat/utils.ts, Frontend/src/mocks/mockMessages.ts
채팅창 UI를 구현했습니다. 아직 component 폴더에 추가해놓고 page에 붙이지는 않았습니다.
page에 통합하면서 반응형, 채팅창 접기 추가 작업 하겠습니다.
채팅창 스크롤 기능 구현 시 `IntersectionObserver` API를 도입했습니다.
- 스크롤 이벤트(`onScroll`)와 스크롤 체크 함수가 스크롤마다 과도하게 호출되어 성능 저하 발생
- 쓰로틀링(Throttling)으로 일부 개선 가능하나 근본적인 해결책이 아님
- 비동기적 DOM 요소 감지로 성능 최적화
- 명시적인 스크롤 이벤트 의존성 제거
- 선언적이고 깔끔한 코드 구현 가능
```typescript
useEffect(() => {
const observer = new IntersectionObserver(
([entry]) => {
const isScrolled = !entry.isIntersecting;
setShowScrollButton(isScrolled);
},
{
root: chatRef.current,      // 관찰 대상의 부모 요소
threshold: 1,               // 요소가 100% 보일 때 콜백 실행
rootMargin: '-16px',       // 관찰 영역 조정
},
);
if (bottomRef.current) {
observer.observe(bottomRef.current);
}
return () => observer.disconnect();
}, [isExpanded]);
```
- closes
=> [Feature] 채팅창 UI 구현

Frontend/src/components/VideoPlayer/index.tsx, Frontend/src/pages/StudioPage/index.tsx
=> [Fix] 배포 위한 빌드 오류 수정

Frontend/src/components/layout/Navbar.tsx, Frontend/src/pages/StudioPage/index.tsx, Frontend/src/routes/index.tsx
=> [Feature] StudioPage UI 구현

Frontend/src/components/layout/Navbar.tsx
배포한 페이지에서 StudioPage 404 오류 해결
* Navbar a태그 -> NavLink
* netlify.toml 추가
=> [Fix] 배포 페이지에서 StudioPage 404 오류 해결

Frontend/package-lock.json, Frontend/src/pages/LivePage/index.tsx
- mockdata -> 실제 데이터 변경으로 생기는 충돌 해결
=> [Fix] mockdata에서 서버에서 받아온 데이터 변경으로 생기는 변경사항 및 충돌

Frontend/package-lock.json, Frontend/src/components/VideoPlayer/useHls.ts
=> [Fix] 안쓰는 import 삭제

Backend/package-lock.json, Backend/package.json, Backend/src/auth/auth.controller.ts, Backend/src/auth/auth.module.ts, Backend/src/auth/auth.service.ts, Backend/src/auth/guards/jwt-auth.guard.ts, Backend/src/auth/strategies/github.strategy.ts, Backend/src/auth/strategies/google.strategy.ts, Backend/src/auth/strategies/jwt.strategy.ts, Backend/src/auth/strategies/naver.strategy.ts, Backend/src/config/typeorm.config.ts, Backend/src/lives/entity/live.entity.ts, Backend/src/users/dto/create.user.dto.ts, Backend/src/users/users.controller.ts, Backend/src/users/users.module.ts, Backend/src/users/users.service.ts
- 회원가입 구현 OAuth 와 users 모듈 결합
- CLIENT_URL 환경 변수 추가
- uuid (36자) 와 맞게 스키마 구성
- 로컬에서 회원가입 확인
- closes #137 
-
=> [Feature] OAuth 를 통한 회원가입 및 로그인 구현

Frontend/netlify.toml, Frontend/src/config/env.ts, Frontend/src/pages/LoginPage/LoginCallback.tsx, Frontend/src/routes/index.tsx
=> [Fix] OAuth 배포 오류 수정

Frontend/netlify.toml, Frontend/src/App.tsx, Frontend/src/apis/axios.ts, Frontend/src/pages/LoginPage/LoginCallback.tsx, Frontend/src/routes/ProtectedRoute.tsx, Frontend/src/store/useAuthStore.ts
=> [Fix] OAuth 백엔드 연동 오류 수정

Backend/src/lives/lives.controller.ts
=> [Fix] srs webhook 사양에 맞게 방송 시작 api 응답 바디 변경

Frontend/src/config/env.ts, Frontend/src/store/useAuthStore.ts
=> [Fix] redirect URI 환경변수 수정

Backend/src/auth/auth.controller.ts, Backend/src/auth/auth.service.spec.ts, Backend/src/main.ts
- cors 및 쿠키 설정 변경
```
res.cookie('jwt', jwt, {
httpOnly: true,
secure: true,
maxAge: 36000000, // 10시간
sameSite: 'none', //' lax' 에서 변경
});
```
```
app.enableCors({
// CORS 설정
origin: configService.get<string>('CORS') || '*',
credentials: true,
methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
allowedHeaders: ['Content-Type', 'Authorization']
});
```
- CORS 설정 추가
=> [Config] cors 및 쿠키 설정 변경

Backend/src/auth/auth.controller.ts, Backend/src/auth/strategies/github.strategy.ts
현재 클라우드 인스턴스에서 `InternalOAuthError: Failed to fetch user emails` 오류가 발생하고 있습니다. 이것이 local에서는 확인 되지 않고 있습니다. 그래서 console.log 와 함께. 스코프를 email 에서 user 로 바꿔서 로그인을 진행해야할 거 같습니다.
=> [Fix] github oauth 스코프 변경

Frontend/src/hooks/useAuth.ts, Frontend/src/main.tsx, Frontend/src/pages/LoginPage/LoginCallback.tsx, Frontend/vite.config.ts
* 개발 환경에서 REACT.striceMode 때문에 2번 요청되어 1회용인 access token 2번 사용되는 오류 해결
* scope 수정
=> [Fix] 프론트엔드 OAUTH 관련 버그 수정

Backend/src/app.module.ts, Backend/src/auth/auth.controller.ts, Backend/src/auth/auth.module.ts, Backend/src/auth/auth.service.ts, Backend/src/auth/strategies/github.strategy.ts, Backend/src/auth/strategies/google.strategy.ts, Backend/src/auth/strategies/jwt.strategy.ts, Backend/src/auth/strategies/naver.strategy.ts, Backend/src/main.ts, Backend/src/users/dto/create.user.dto.ts, Backend/src/users/entity/user.entity.ts, Backend/src/users/users.module.ts, Backend/src/users/users.service.ts, Frontend/src/store/useAuthStore.ts
google OAuth 를 통한 accessToken, refreshToken 발급 확인 accessToken 은 json 으로 보내고, refreshToken  은 쿠키로 전달
1. 서버 환경 변수 일치
2. 스코프 맞추기
3. 인메모리 DB 에서 되던거 -> sql로
4. 환경변수 맞춰서 배포
5. 로그아웃, refresh token -> api문서 참고
=> [Feature] google OAuth accessToken, refreshToken 생성

Backend/src/users/entity/user.entity.ts
로컬 mysql 하고 충돌이 나서 확인해보니 user entity 가 변경되어 있었음. 다시 원상 복귀함
user entity
=> [Refact] user entity 이전 상태로 복귀

Backend/src/auth/strategies/google.strategy.ts
배포 환경에서 google Oauth 만 되지 않았습니다. 디버깅합니다.
=> [Fix] google Oauth 디버깅

Backend/src/lives/lives.controller.ts
JWT 인증 정보를 통해 스트리밍 키를 조회하는 API를 추가하였습니다.
가드를 이용해 JWT 정보를 이용해 가져오므로 별도의 경로 변수는 불필요합니다.
- 스트리밍키 조회 API 추가
- 
- 테스트 추가
=> [Feature] 스트리밍키 조회 API 추가

Backend/src/lives/lives.controller.ts
유저 엔티티 주입을 위해 req 데코레이터 주입한 후 거기에 결합
- 유저 엔티티 주입 안되는 문제 수정
=> [Fix] 스트리밍 키 조회 API 오류 수정

Backend/src/auth/guards/websocket-auth.guard.ts, Backend/src/auth/strategies/websocket.strategy.ts, Backend/src/chats/chats.gateway.ts
웹소켓 연결 시 인증을 수행하도록 하였습니다.
- 소켓 연결 시 가드를 이용해 인증 수행
- 로그인 되지 않은 유저가 채팅을 전송하였을 시 공지 메시지 전송
- 테스트 추가
=> [Feature] 채팅 시 인증 처리 추가, 메시지 양식 수정

Frontend/src/apis/user.ts, Frontend/src/components/common/Toast/index.tsx, Frontend/src/components/layout/Navbar.tsx, Frontend/src/components/layout/NavbarMini.tsx, Frontend/src/hooks/useUser.ts, Frontend/src/pages/MyPage/index.tsx, Frontend/src/routes/index.tsx, Frontend/src/types/user.ts
=> [Feature] 마이페이지, 유저 정보 수정

Backend/src/chats/chats.gateway.ts
인증 로직이 있는 상태에서 프론트 작업이 힘들고 현재 제대로 작동하지 않고 있는 관계로 관련 코드 제거합니다.
=> [Feature] 채팅 발송 인증로직 제거

Frontend/src/apis/live.ts, Frontend/src/hooks/useLive.ts
=> [Fix] : streaming key api 수정

Frontend/src/pages/StudioPage/StreamSettings.tsx, Frontend/src/pages/StudioPage/index.tsx
=> [Fix] 스트림 키 오류해결

Backend/package-lock.json, Backend/package.json, Backend/src/auth/auth.controller.ts, Backend/src/users/users.controller.ts, Backend/src/users/users.service.ts
1. 유저 프로필 업로드 api를 구현했습니다.
- 이미지 파일을 5MB 크기 제한이 있습니다.
2. 쿠키에 서브도메인(`.lico.digital`을 추가했습니다.
- 이렇게 하면 lico.digital, api.lico.digital, www.lico.digital 등 모든 서브도메인에서 쿠키에 접근할 수 있습니다.
-
- closes #이슈번호
=> [Feature] 유저 프로필 업로드 api

Backend/src/chats/chats.gateway.ts
채팅방 소켓 연결이 끊어졌다가 재연결 될 시 시청자수에 재연결된 인원도 포함되도록 수정하였습니다.
메시지 전송 시 로그인한 유저인지 확인하는 조건문을 복구하였습니다.
- 채팅방 재연결 시 시청자수 반영
- 메시지 전송 시 로그인한 유저인지 확인하는 조건문 복구
- olchats json이 아닌 객체 배열로 전송
- closes #187 
- 테스트 추가
=> [Feature] 채팅방 재연결 시 시청자수 변경, 메시지 전송 로그인 유저 검증 복구

Backend/src/chats/chats.gateway.ts
서버에서 클라이언트로 메시지 전송 시 json문자열[] 의 형식으로 전송하도록 변경하였습니다.
- 새로운 메시지를 객체 배열이 아닌 json 문자열 배열로 클라이언트로 전송하도록 변경
=> [Fix] chat 이벤트 메시지 전송 형식 통일

Backend/server/encoding/cleanup.sh, Backend/server/encoding/nginx.conf, Backend/server/encoding/stream_process.sh
인코딩 설정을 수정하여 cpu 사용량을 낮추고 좀더 낮은 지연시간으로 송출이 되도록 하였습니다.
-  인코딩 옵션 변경
-  1080p 화질 제거
- 인코딩 preset ultrafast에서 veryfast로 변경
- hls segment fmp4로 변경
- split_by_time 옵션 제거
- independent segment, append list 옵션 추가
- nginx config에서 exec_publish_done으로 cleanup 스크립트 실행하지 않고, stream_process 스크립트에서 실행하도록 수정
기존에 비해 cpu 사용량이 10%포인트가량 감소
지연 시간을 10초 이내로 줄임
=> [Config] 인코딩 설정 변경

Frontend/src/apis/follow.ts, Frontend/src/components/common/Buttons/FollowButton.tsx, Frontend/src/hooks/useFollow.ts, Frontend/src/pages/LivePage/LiveInfo.tsx, Frontend/src/pages/LivePage/index.tsx, Frontend/src/types/live.ts
=> [Fix] 채널 id 대신 스트리머 id로 팔로우

Frontend/src/apis/follow.ts, Frontend/src/hooks/useFollow.ts, Frontend/src/pages/FollowingPage/OfflineCard.tsx
* 팔로우/언팔로우 안바뀌는 오류 수정
* 서버에서 성공 응답시 UI 즉시 업데이트
* 캐시 동기화
* 즉시 버튼 상태 변경 확인
=> [Fix] 버튼 상태 바뀌도록

Frontend/src/apis/follow.ts, Frontend/src/components/common/Buttons/FollowButton.tsx, Frontend/src/hooks/useFollow.ts, Frontend/src/pages/FollowingPage/OfflineCard.tsx, Frontend/src/pages/LivePage/LiveInfo.tsx, Frontend/src/types/live.ts
* streamerId 타입 string -> number 변경
* streamerId 타입 string -> number 변경
=> [Fix] streamerId 타입 string -> number 변경

.github/workflows/develop-deploy.yml, Backend/server/api/deploy.sh, Backend/src/config/typeorm.config.ts
디벨롭 브랜치의 백엔드 소스 코드가 변경될 경우 api 서버가 자동으로 배포되도록 깃헙 액션을 추가하였습니다.
- dev api 서버 ssh 키 추가
- dev api 서버 배포 깃헙 액션 워크 플로우 추가
=> [CI/CD] dev api 서버 깃헙 액션 배포 워크플로우 및 배포 스크립트 추가

Backend/src/lives/lives.controller.ts, Backend/src/lives/lives.service.ts, Backend/src/main.ts
인기(viewers) 순 정렬 쿼리 파라미터 구현했습니다. 또한 카테고리 업데이트에서 유저 인증을 추가 했습니다. main.ts 에 cors 메서드 중 patch 를 추가 했습니다.
=> [Feature] 인기순 파라미터 구현

.github/workflows/develop-deploy.yml, .github/workflows/main-deploy.yml
메인 브랜치의 백엔드 코드에 push 발생 시 배포가 자동으로 이루어지도록 워크플로우를 추가하였습니다.
웹훅을 이용해 배포 결과를 프로젝트 채널에 알려주도록 하였습니다.
- main 브랜치(프로덕션) 배포 워크플로우 추가
- 웹훅 알림 설정 추가
=> [CI/CD] 메입 브랜치 배포 워크플로우 추가 및 슬랙 알림 추가

Frontend/src/pages/StudioPage/WebRTCStream.ts, Frontend/src/pages/StudioPage/index.tsx
* WHIP 연결 형식 맞추기
* WHIP 연결 형식 맞추기
=> [Feature] WHIP 연결 형식 맞추기

Frontend/src/apis/live.ts, Frontend/src/components/VideoPlayer/Control/SettingsControl.tsx, Frontend/src/components/VideoPlayer/Control/VolumeControl.tsx, Frontend/src/components/VideoPlayer/Control/index.tsx, Frontend/src/components/VideoPlayer/index.tsx, Frontend/src/components/channel/ChannelCard/ChannelThumbnail.tsx, Frontend/src/components/channel/ChannelCard/ThumbnailSkeleton.tsx, Frontend/src/components/common/Badges/Badge.tsx, Frontend/src/hooks/useHls.ts, Frontend/src/hooks/useLive.ts, Frontend/src/pages/LivePage/index.tsx, Frontend/src/pages/LivesPage/index.tsx, Frontend/src/types/live.ts
- 비디오 플레이어 컨트롤 가시성 개선 => 색상과 사이즈를 변경했습니다.
- 자동 화질 시, 현재 어떤 화질인지 안내 문구 추가
- 썸네일 이미지 jpg로 변경
- hls.js 옵션을 현재 저희 서비스 m3u8 파일, 세그먼트 크기에 맞춰 최적화했습니다.
- 자동 생성 썸네일이 없을 시, 이미지 로드에서 error일 때 스켈레톤 UI를 추가하고 이미지 onLoad 시 썸네일이 리랜더링 되도록 했습니다.
- LivePage 방송 정보가 30초 간격으로 polling으로 업데이트 됩니다.
- closes #이슈번호
=> [Feature] LivePage 방송정보 업데이트, 비디오 플레이어 개선

Frontend/src/config/env.ts, Frontend/src/hooks/useCanvasElement.ts, Frontend/src/pages/StudioPage/StreamContainer.tsx, Frontend/src/pages/StudioPage/StreamSettings.tsx, Frontend/src/pages/StudioPage/WebRTCStream.ts, Frontend/src/pages/StudioPage/WebStreamControls.tsx, Frontend/src/pages/StudioPage/index.tsx, Frontend/src/types/canvas.ts
=> [Refactor] WebStudio 리팩토링

Frontend/src/components/chat/ChatInput.tsx, Frontend/src/pages/CategoryPage/CategoryDetailPage.tsx, Frontend/src/pages/FollowingPage/index.tsx
- 로그인 확인 툴팁 z-index 최상단에 위치하도록 변경
- 카테고리 페이지, 팔로우 페이지 썸네일 시청자 수 표시되도록 변경
- closes #이슈번호
=> [Fix] 4주차 피드백 적용, 수정

Backend/apps/api/src/app.module.ts, Backend/apps/api/src/auth/guards/jwt-auth.guard.ts, Backend/apps/api/src/config/logger.config.ts, Backend/apps/api/src/main.ts
모니터링 시스템 구축을 위해 이것 저것 학습하면서, winston 도 있는데 logging 도 있어야 하나 싶어서 전역에 winston 을 세팅했습니다. (api 한정) 그런데, 막상 적용하려고 보니까. 전반적인 코드에 logger 를 추가해야 한다는 점을 깨달았습니다. 일단 PR 은 올리지만, 데일리 스크럼 때, 이야기 해보고 의논하는 것이 좋을 거 같습니다.
=> [Feature] logging을 위한 winston 세팅

Frontend/src/apis/live.ts, Frontend/src/assets/icons/eraserCursor.svg, Frontend/src/assets/icons/pencilCursor.svg, Frontend/src/hooks/useDrawing.ts, Frontend/src/hooks/useLive.ts, Frontend/src/hooks/useText.ts, Frontend/src/pages/StudioPage/Modals/Palette.tsx, Frontend/src/pages/StudioPage/Modals/TextSetting.tsx, Frontend/src/pages/StudioPage/StreamContainer.tsx, Frontend/src/pages/StudioPage/WebRTCStream.ts, Frontend/src/pages/StudioPage/WebStreamControls.tsx, Frontend/src/pages/StudioPage/index.tsx, Frontend/src/styles/index.css, Frontend/src/types/canvas.ts
- WebStudio 그리기, 지우개, 텍스트
https://github.com/user-attachments/assets/afaf7912-cc65-4e15-96ab-12402866f42a
=> [Feature] WebStudio 그리기, 지우개, 텍스트

Frontend/src/apis/chat.ts, Frontend/src/components/chat/ChatWindow.tsx, Frontend/src/config/env.ts
- 백엔드 변경사항에 맞춰 chat 발송을 post로 변경했습니다.
- closes #이슈번호
=> [Fix] chat 발송 Post로 변경

Backend/apps/api/src/app.module.ts, Backend/apps/api/src/common/filters/http-exception.filter.ts, Backend/apps/api/src/common/interceptors/monitoring.interceptor.ts, Backend/apps/api/src/common/middleware/request-time.middleware.ts, Backend/apps/api/src/common/services/cloud-insight.service.ts
네이버 클라우드의 Cloud Insight를 활용하여 애플리케이션에서 요청 및 응답 정보를 수집하고 모니터링할 수 있도록 기능을 추가하였습니다.  그 과정에서 인터셉터와 필터가 수정 및 생성되었습니다. 주요 변경 사항을 참고해주세요.
근데, 로컬에서 test하기에는 실제 cloud insight 에 적용되는지 확인할 수 없었습니다. 아무래도 일단 merge 하고 작동을 확인해야할 거 같습니다.
- 응답 시간을 계산해야해서 미들웨어를 생성하고 전역으로 적용했습니다.
=> [Feature]: 모니터링을 위한 인터셉터 & 필터

Frontend/src/components/chat/ChatMessage.tsx, Frontend/src/components/chat/ChatProfileModal.tsx, Frontend/src/components/chat/ChatSettingsMenu.tsx, Frontend/src/components/chat/ChatWindow.tsx, Frontend/src/components/chat/PendingMessageNotification.tsx, Frontend/src/hooks/chat/useChatMessages.ts, Frontend/src/hooks/chat/useChatScroll.ts, Frontend/src/hooks/chat/useChatSocket.ts, Frontend/src/pages/ChatPopupPage/index.tsx, Frontend/src/routes/index.tsx, Frontend/src/types/live.ts, Frontend/src/utils/format.tsx
- 채팅을 새창에 띄우는 팝업모드를 구현했습니다.
- 클린 봇 모드 토글과 같은 타임스탬프 모드를 구현했습니다.
- 클린 봇이 토글에 따라 검열/비검열이 되도록 로직을 수정했습니다.
- 타임스탬프 - 닉네임 - 채팅내용 간 채팅창에 맞도록 css 수정했습니다.
- closes #이슈번호
=> [Feature] 채팅 팝업 모드, 타임스탬프 모드 구현, 클린 봇 수정

Frontend/src/components/chat/ChatWindow.tsx, Frontend/src/hooks/useHls.ts
- 클린 봇 off 일 때 새로들어온 메세지가 on으로 바꿔도 필터링이 안되는 버그 수정
- hls.js 국희님이 말해주신 옵션으로 변경했습니다.
- closes #이슈번호
=> [Fix] hls.js 옵션 수정, 클린봇 버그 수정

Frontend/src/layouts/Layout.tsx, Frontend/src/pages/CategoryPage/index.tsx, Frontend/src/pages/LivePage/index.tsx, Frontend/src/pages/StudioPage/index.tsx
- 채팅창 잠금 로직이 잘못 적용되어 있는 것을 수정했습니다.
- 사이드바 잠금 로직 수정했습니다.
- 스튜디오 페이지 채팅에도 반응형, 잠금 추가했습니다.
- 레이아웃 main에 min-w 를 적용했는데, 다른 페이지와 서로 달라서 충돌이 났습니다. 각 페이지마다 최적화 하는 것으로 수정했습니다.
- closes #이슈번호
=> [Fix] 채팅창 잠금 기능, 반응형 최소 넓이 등 레이아웃 관련 버그 수정

Frontend/src/components/VideoPlayer/index.tsx, Frontend/src/hooks/useCheckStream.ts, Frontend/src/hooks/useDelayedLoading.ts, Frontend/src/hooks/useHls.ts, Frontend/src/pages/CategoryPage/index.tsx, Frontend/src/pages/FollowingPage/index.tsx, Frontend/src/pages/LivePage/index.tsx, Frontend/src/pages/LivesPage/index.tsx, Frontend/src/pages/StudioPage/index.tsx
- 방송 시작 시 오브젝트 스토리지를 체크하는 커스텀 훅을 추가했습니다.
- 로딩이 너무 짧은 경우 보이지 않게 하는 커스텀 훅을 추가했습니다.
- closes #이슈번호
=> [Feature] 방송 시작, 종료시 메세지 추가 / 로딩 딜레이 훅 구현

Backend/apps/api/src/chats/chats.service.ts
채팅 공통 큐, 캐시를 사용하던 부분을 채널별로 개별 캐시, 큐를 생성하도록 변경하고 방송 시작 시 채팅내역, 캐시, 큐를 모두 지우도록 변경
=> [Merge] 6주차 메인 브랜치 배포 - 채팅 핫픽스

Frontend/index.html
HTML 편집 중 html 태그가 2번 중복되어 있는 문제 해결
- closes #이슈번호
=> [Fix] HTML 태그 중복 문제 해결

Backend/apps/api/src/chats/chats.service.ts
HTML 태그 중복 문제 수정
- closes #이슈번호
=> [Fix] 메인 브랜치 - HTML 태그 중복 수정
