Frontend/src/components/LiveInfo/StreamerInfo.tsx
Frontend/src/components/LiveInfo/index.tsx
Frontend/src/components/VideoPlayer/index.tsx
Frontend/src/components/chat/ChatHeader.tsx
Frontend/src/components/chat/ChatMessage.tsx
Frontend/src/components/chat/ChatWindow.tsx
Frontend/src/components/common/Buttons/ChatOpenButton.tsx
Frontend/src/components/layout/NavbarMini.tsx
Frontend/src/hooks/useMediaQuery.ts
Frontend/src/layouts/Layout.tsx
Frontend/src/pages/LivePage/index.tsx
Frontend/src/store/useLayoutStore.ts
Frontend/tsconfig.app.json
Frontend/vite.config.ts

- LivePage 채팅창 구현 및 동적 레이아웃 시스템 구축
- 뷰포트 기반 반응형 제어를 위한 `useMediaQuery` 훅 구현
- 복잡한 레이아웃 상태 관리를 위한 `useLayoutStore` (Zustand) 구현
- Navbar 축소/확장
- 채팅창 접기/펼치기
- 극장 모드 전환
- **1200px**: Navbar 자동 축소/확장
- **700px**: 채팅창 자동 접기/펼치기
- 극장 모드에서는 세로 모드로 전환
- 채팅창 수동 접기 시 자동 접기/펼치기 비활성화
- 극장 모드 전환 시 Navbar 자동 접기
- 채팅창 접힘 상태에서 우측 상단에 토글 버튼 고정 배치

[Feature] LivePage 동적 레이아웃 & 채팅 컴포넌트 구현

---

Frontend/netlify.toml

배포한 페이지에서 StudioPage 404 오류 해결
* Navbar a태그 -> NavLink
* netlify.toml 추가

[Fix] 배포 페이지에서 StudioPage 404 오류 해결

---

Frontend/package-lock.json
Frontend/package.json
Frontend/src/components/VideoPlayer/Control/SettingsControl.tsx
Frontend/src/components/VideoPlayer/Control/VolumeControl.tsx
Frontend/src/components/VideoPlayer/Control/index.tsx
Frontend/src/components/VideoPlayer/index.tsx
Frontend/src/components/chat/ChatInput.tsx
Frontend/src/components/chat/ChatWindow.tsx
Frontend/src/components/common/Buttons/ChatOpenButton.tsx
Frontend/src/components/common/Buttons/FollowButton.tsx
Frontend/src/constants/chat/color.ts
Frontend/src/constants/chat/input.ts
Frontend/src/layouts/Layout.tsx
Frontend/src/pages/FollowingPage/index.tsx
Frontend/src/pages/LivePage/index.tsx
Frontend/src/pages/StudioPage/ControlButton.tsx
Frontend/src/pages/StudioPage/StreamInfo.tsx
Frontend/src/pages/StudioPage/StreamSettings.tsx
Frontend/src/pages/StudioPage/WebStreamControls.tsx
Frontend/src/pages/StudioPage/index.tsx
Frontend/src/store/useFollowStore.ts
Frontend/src/utils/chatUtils.ts
Frontend/tailwind.config.js

- 비디오플레이어, 스튜디오 페이지 컴포넌트 간단하게 분리했습니다.
- 스크롤바 없애기를 테일윈드 플러그인을 설치해 간소화 했습니다.
- 스튜디오 페이지 채팅창도 접기 연결했습니다.
- `setUseChannel`하는 과정에서 조건 비교를 잘못하고 있는 버그를 수정했습니다. [링크](https://far-woodwind-e60.notion.site/live-id-url-08638f25e9464fdf98827bfcbde802f5?pvs=4)
- 기존 useStore.ts의 이름을 useFollowStore.ts로 변경했습니다.
- 하단 이동 버튼이 입력창 크기에 따라 위치가 변하도록 수정했습니다.
- 기존 chat 컴포넌트 내부에 있던 util.ts 과 constant.ts를 분리했습니다.

[Refactor] 컴포넌트 분리, 버그 수정

---

Backend/src/lives/dto/live.dto.ts
Backend/src/lives/dto/lives.dto.ts
Backend/src/lives/entity/live.entity.ts
Backend/src/lives/lives.controller.ts
Backend/src/lives/lives.service.spec.ts
Backend/src/lives/lives.service.ts

ingest 서버, encoding 서버에서 방송 시작, 종료 시 정보 갱신을 위해 필요한 API를 추가하였습니다.
- GET /lives/channel-id/{streamingKey} : 채널 아이디 조회 API
- POST /lives/onair/{streamingKey} : 방송 시작 요청 - 방송 상태와 방송 시작 시간을 갱신합니다.
- DELETE /lives/onair/{streamingKey} : 방송 종료 요청 - 방송 상태를 갱신합니다.
- #143 수정
- #142 수정
- closes #150 #151 #143 #142 #149

[Feature] 라이브 방송 시작,종료 알림 API 및 채널ID 획득 API 추가(서버용)

---

Backend/src/lives/lives.controller.ts

[Fix] srs webhook 사양에 맞게 방송 시작 api 정상 응답 200으로 변경

---

Backend/src/auth/strategies/github.strategy.ts
Backend/src/users/users.service.ts

`lico.digital/live` 랜더링이 되지 않아서 log를 확인해보니,
```[Nest] 45393  - 11/12/2024, 1:53:55 AM   ERROR [ExceptionsHandler] Cannot read properties of null (reading 'nickname')
TypeError: Cannot read properties of null (reading 'nickname')
at LiveEntity.toLivesDto (/root/lico/Backend/dist/lives/entity/live.entity.js:23:38)
at /root/lico/Backend/dist/lives/lives.service.js:26:43
at Array.map (<anonymous>)
at LivesService.readLives (/root/lico/Backend/dist/lives/lives.service.js:26:22)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async LivesController.getLives (/root/lico/Backend/dist/lives/lives.controller.js:24:16)
```
- 원인을 찾아보니, user 의 lives_id 가 null 로 되어 있었습니다. 그래서수정을 했습니다.
```
// UsersService.createUser 메서드 
const newUser = manager.create(UserEntity, { …
```

[Fix]: live_id 값이 null이 되는 거 수정

---

Frontend/src/components/LiveInfo/StreamingTimer.tsx
Frontend/src/components/LiveInfo/index.tsx
Frontend/src/components/VideoPlayer/LoadingSpinner.tsx
Frontend/src/components/VideoPlayer/index.tsx
Frontend/src/hooks/useHls.ts
Frontend/src/pages/LivePage/index.tsx
Frontend/src/pages/StudioPage/index.tsx
Frontend/src/styles/index.css

- 비디오 플레이어와 관련된 useHls 훅 작업했습니다.
- 버퍼링 추가했습니다.
- 화질 조정 기능을 위한 함수 구현 했습니다.
- 비디오 플레이어 버퍼링 시 사용할 LoadingSpinner 컴포넌트 작업했습니다.
- 비디오 플레이어 버퍼링 시 적용했습니다.
- LivePage 로딩시 적용했습니다.
- LivePage 방송 시간 추가했습니다. 
```js
hlsInstance.on(Hls.Events.MANIFEST_PARSED, (_, data) => {
const availableQualities = data.levels.map((level, index) => ({
level: index,
height: level.height,
width: level.width,
bitrate: level.bitrate,
}));
setQualities(availableQualities);
});
```
샘플 m3u8 파일을 받았을 때, data를 변환한 결과입니다. 
level이 0이 가장 저화질, 높아질수록 고화질을 뜻합니다.
level : -1 은 '자동'을 뜻합니다.
여러 화질/해상도 버전의 정보를 포함하고 있는 Master Manifest을 따라 자동으로 화질을 설정하게 됩니다.
```
//Master Manifest
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=800000,RESOLUTION=640x360
stream_360p.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1400000,RESOLUTION=842x480 …
```

[Feature] useHls 기능 추가, 로딩 컴포넌트 구현, 방송 시간 계산 컴포넌트 추가

---

Backend/server/encoding/cleanup.sh
Backend/server/encoding/nginx.conf
Backend/server/encoding/stream_process.sh
Backend/server/ingest(srs)/lico.conf
Backend/server/ingest(srs)/nginx.conf
Backend/src/categories/categories.controller.spec.ts
Backend/src/categories/categories.controller.ts
Backend/src/categories/categories.module.ts
Backend/src/categories/categories.service.spec.ts
Backend/src/categories/categories.service.ts
Backend/src/categories/error/error.message.enum.ts
Backend/src/config/typeorm.config.ts
Backend/src/lives/dto/live.dto.ts
Backend/src/lives/dto/lives.dto.ts
Backend/src/lives/entity/live.entity.ts
Backend/src/lives/error/error.message.enum.ts
Backend/src/lives/lives.controller.spec.ts
Backend/src/lives/lives.controller.ts
Backend/src/lives/lives.module.ts
Backend/src/lives/lives.service.spec.ts
Backend/src/lives/lives.service.ts

카테고리에서 미구현하였던 카테고리 방송 목록 조회 API 추가
미디어 서버를 분리하였습니다.
1. ingest 서버는 lico.conf 에 따라 rtmp와 werbrtc 입력을 encoding 서버에 rtmp로 전송합니다.
이때 api 서버에 스트림키에 해당하는 채널이 이미 방송 진행중인지 아닌지를 체크합니다.
크레딧 사정 상 ingest 서버를 dev와 live 환경으로 분리하지 멋하여 api 검증 요청을 내부의 nginx로 보낸 뒤
nginx 에서 api 요청의 body 에 따라 api 서버를 지정하여 요청을 전송합니다.
(설정에서 url만 지정 가능하고 메서드 및 바디가 지정되어있으며 동적 url 생성이 불가능 하여 이러한 방법을 선택하였습니다.)
2. encoding 서버는 nginx-rtmp 모듈을 이용하여 ingest 서버가 rtmp 요청을 전송하면 stream_process.sh 스크립트를 실행하고 전송이 종료되면 cleanup.sh 스크립트를 실행합니다.
stream_process.sh 에서는 여러 화질로 영상을 인코딩하여 오브젝트 스토리지에 저장합니다.
cleanup.sh 에서는 오브젝트 스토리지에 저장된 영상 파일을 제거합니다.
1. 카테고리 방송 목록 조회 API를 추가하였습니다.
2. ingest 서버, encoding 서버에서 사용중인 스크립트 및 nginx 설정 파일을 추가하였습니다.
4. 채널 상세 정보 조회 시 조회된 정보가 없으면 404 에러를 반환하도록 하였습니다.
5. 방송 목록 획득 시 조건을 입력하여 목록을 받아올 수 있게 함수를 리팩터링 하였습니다.

[Feature] 카테고리 방송 목록 조회 API 추가

---

Backend/package-lock.json
Backend/package.json
Backend/src/app.module.ts
Backend/src/config/mysql.config.ts
Backend/src/config/sqlite.config.ts
Backend/src/config/typeorm.config.ts
Backend/src/users/entity/user.entity.ts

프론트 작업의 편의를 위해 .env에서 DB_TYPE을 읽고 그에 따라 typeorm 설정을 동적으로 하여 sqlite 인메모리 모드에서 서버를 띄울 수 있게 하였습니다.
- usersentity enum 컬럼을 sqlite이면 simple-enum 컬럼이 되도록 변경
- mysql.config, sqlite.config 추가
- sqlite 디펜던시를 데브로 변경

[Feature] sqlite 이용하여 별도 DB 설치 없이 로컬호스트에서 서버 띄울 수 있도록 수정

---

Backend/src/auth/auth.controller.ts
Backend/src/auth/auth.service.ts
Backend/src/users/dto/create.user.dto.ts
Backend/src/users/users.service.ts

auth/refresh api 구현했습니다. 프론트에서 테스트 부탁드립니다. 또한 access 토큰에 liveId, chennelId 등을 추가했습니다.

[Feature] auth/refresh api 구현

---

Backend/src/auth/auth.controller.ts
Backend/src/auth/auth.service.ts
Backend/src/users/dto/create.user.dto.ts
Backend/src/users/dto/update.user.dto.ts
Backend/src/users/users.controller.ts
Backend/src/users/users.service.ts

`/users/{userId}` method `PUT`, `GET` 2개 api 구현 
- `PUT` 메서드는 본인이 프로필 정보를 바꾸는 요청
- `GET` 메서드는 임의의 사용자가 다른 사용자의 프로필 이미지나 닉네임을 클릭하거나, 본인의 프로필 페이지에 들어갈 때, 요청
- `/users/dto/update.user.dto.ts` 생성 
- `users.service.ts` 의 `updateUser` 메서드 구현
- `users.controller.ts` 의 `updateProfile` 메서드 구현
```
// 20241114014910
// http://localhost:3001/users/1
{
"users_id": 1,
"nickname": "최명권",
"profile_image": "https://lh3.googleusercontent.com/a/ACg8ocL6Ts4DJlhhoZAYnORFNloeRd11R63nW09FMyDjccfpWoWnud8g=s96-c",
"created_at": "2024-11-13T12:50:11.660Z"
}
```
- 이미지는 아니지만, `/users/{userId}` 를 `GET` 했을 때 결과
- closes #141

[Feature] users api 구현

---

Frontend/src/apis/axios.ts

*  토큰 요청시 401 응답 받았을 때 무한루프 대신 홈으로 리다이렉트
*  토큰 요청시 401 응답 받았을 때 무한루프 대신 홈으로 리다이렉트

[Fix] 토큰 요청시 401 응답 받았을 때 무한루프 대신 홈으로 리다이렉트

---

Backend/src/auth/auth.controller.ts

`.env` 파일에 변수 IS_PRODUCTION 를 추가 했습니다. 
```
IS_PRODUCTION=false 
```
기존에는 다음과 같이 cookie 설정을 했습니다.
```
res.cookie('refreshToken', '', {
httpOnly: true,
secure: process.env.NODE_ENV === 'production', // undefined
sameSite: 'none',
maxAge: 0,
path: '/auth',
});
```
이걸 
```
res.cookie('refreshToken', '', {
httpOnly: true,
secure: this.isProduction,
sameSite: this.isProduction ? 'none' : 'lax',
maxAge: 0,
path: '/auth',
});
```
- 이렇게 환경 변수로 관리 되도록 했습니다.
- 왜냐하면 개발 환경(`http`)과 배포 환경(`https`) 의 차이가 있기 때문입니다.
- 이로 인해서 refreshToken 이 개발 환경에서 들어오지 않는 문제가 있었습니다.
옵션 | 배포 환경 | 개발 환경
-- | -- | --
httpOnly | true | true
secure | true | false
sameSite | 'none' | 'lax'

[Feature] IS_PRODUCTION 환경 변수로 cookie 관리

---

Backend/src/app.module.ts
Backend/src/auth/auth.controller.ts
Backend/src/follow/follow.controller.spec.ts
Backend/src/follow/follow.controller.ts
Backend/src/follow/follow.module.ts
Backend/src/follow/follow.service.spec.ts
Backend/src/follow/follow.service.ts
Backend/src/users/dto/create.user.dto.ts
Backend/src/users/entity/user.entity.ts

follow-api 생성했습니다.
1. 팔로우한 스트리머 목록을 조회하는 목적이지만, 스트리머 클릭 시 채널로 이동하는 것도 고려하고 있어서 join 사용은 불가피
- 대신 완전 방송 목록은 아니라서 불필요한 category 하고 join 은 제외
- 예시(수정 후)
```
[
{
"categoriesId": 1,
"categoriesName" : "카테고리 이름"
"livesName": "방송 이름",
"channelId" : "채널ID",
"usersNickname" : "스트리머 닉네임",
"usersProfileImage": "스트리머 프로필 이미지"
"onAir":"현재 방송 상태"
},
// 계속
]
```
- 예시(수정 전)
```
[
{
"channelId" : "채널ID",
"usersNickname" : "스트리머 닉네임",
"usersProfileImage": "스트리머 프로필 이미지"
"onAir":"현재 방송 상태"
},
// 실제
{
"channelId": "7a4c0afc-26ca-470e-9655-37cfcbdc1126",
"usersNickname": "구글닉네임",
"usersProfileImage": "https://kr.object.ncloudstorage.com/lico.image/profile-images/1731599665735-zoom_%C3%A1%C2%84%C2%86%C3%A1%C2%85%C2%A6%C3%A1%C2%86%C2%B7%C3%A1%C2%84%C2%87%C3%A1%C2%85%C2%A5%C3%A1%C2%84%C2%89%C3%A1%C2%85%C2%B5%C3%A …
```

[Feature] follow-api 생성

---

Backend/src/app.module.ts
Backend/src/chats/chats.module.ts
Backend/src/config/redis.config.ts
Backend/src/lives/dto/live.dto.ts
Backend/src/lives/dto/lives.dto.ts
Backend/src/lives/dto/status.dto.ts
Backend/src/lives/dto/update.live.dto.ts
Backend/src/lives/entity/live.entity.ts
Backend/src/lives/lives.controller.ts
Backend/src/lives/lives.module.ts
Backend/src/lives/lives.service.ts

라이브 테이블에 시청자수 컬럼 추가 및 갱신 정보 획득이 가능한 API를 추가하였습니다.
시청자수 쓰기에 write-back 전략을 갱신 정보 획득에 read-through 전략을 사용하였습니다.
- 시청자수 정보 라이브 테이블에 추가
- 라이브 정보 DTO들에 시청자수 정보 추가
- 채팅에 연결된 유저들 정보를 이용하여 시청자수 주기적인 쓰기 구현
- closes #218 #216 
- 테스트 추가

[Feature] 라이브 갱신 필요 정보 획득 API 추가

---

Backend/src/categories/categories.controller.ts
Backend/src/lives/lives.controller.ts
Backend/src/lives/lives.service.ts

인기, 추천, 최신순 그리고 무한스크롤을 지원하기 위해서 lives-api 에 파라미터 응답 추가했습니다.
참고: 아마도 이 PR 은 앞에 국희님 PR 하고 충돌이 날 수 있을 거 같습니다. 충돌 처리하기 어려울 경우, close 하고 다시 작성하는 것이 좋을 거 같습니다. 인기순 기능 때문에 어차피 다시 코드를 살펴봐야할 거 같기 때문입니다.
첫 번째 요청:
```
GET http://localhost:3000/lives
```
```
기본값: sort=latest, limit=20, offset=0
```
두 번째 요청:
```
GET http://localhost:3000/lives?sort=latest&limit=20&offset=20
```
세 번째 요청:
```
GET http://localhost:3000/lives?sort=latest&limit=20&offset=40
```
기본 요청
```
http://localhost:3000/categories/1/lives
```
파라미터 추가
```
http://localhost:3000/categories/1/lives?sort=latest&limit=20&offset=0
```
- 시청자 수 조회 기반으로 인기 파라미터를 완성하기

[Feature] lives-api 파라미터 응답 추가

---

Backend/src/lives/dto/live.dto.ts
Backend/src/lives/entity/live.entity.ts

팔로우 기능을 구현하기 위해서 **라이브 방송 상세 정보 조회**(  **엔드포인트:** `GET /lives/{channelId}`) 을 보낼 때, 데이터에 streamerId 가 있어야해서 dto 하고 엔티티에 streamerId를 추가했습니다.

[Fix] : 라이브 상세 정보 조회에 streamerId를 추가

---

Backend/src/lives/dto/lives.dto.ts
Backend/src/lives/entity/live.entity.ts

프론트에드 요청에 따라서 방송 목록 조회에도 streamerId 추가합니다.

[Fix] lives 에도 streamerId 추가

---

Frontend/src/components/chat/ChatWindow.tsx

- 로그인일 때만 accessToken을 auth 옵션에 보내도록 했습니다.
- 비로그인일 경우 그냥 connect 하게 됩니다.
```js
const socket = io(`${config.apiBaseUrl}/chats`, {
transports: ['websocket'],
...(isLoggedIn && {
auth: {
token: accessToken,
},
}),
});
```
- closes #이슈번호

[Fix] 채팅 연결 auth 수정

---

Backend/server/encoding/stream_process.sh

ffmpeg 프리셋을 다시 ultrafast로 변경하여 cpu부하 감소 및 인코딩 속도 증가
기존 원본 스트림에 대하여 해상도 별로 인코딩작업을 수행하던 것을 720p 생성 시에만 수행하고 480p와 360p는 split 필터를 이용해 720p 스트림을 기반으로 스케일링하여 생성 오디오도 720p 생성 시에만 인코딩하고 나머지 해상도에서는 인코딩된 오디오를 복사
썸네일 생성 시에도 인코딩하지않고 스케일링만 수행하여 썸네일 생성, 썸네일 형식 jpg로 변경
- 인코딩 옵션 변경
- 썸네일 파일 형식 변경
단일 방송 송출 시의 CPU 부하가 30% 밑으로까지 내려감

[Config] 인코딩 설정 변경하여 CPU 부하 감소 및 인코딩 속도 증가

---

Backend/src/chats/chats.gateway.ts

📝 PR 설명
채팅 코드에서 채팅 리스트 크기를 매직넘버에서 상수로 변경하였습니다.
저장한 채팅 리스트 리사이즈 함수를 제거하였습니다.
✅ 주요 변경 사항
채팅 리스트 리사이즈 함수 삭제
채팅 리스트 최대 사이즈 상수화

[Refactor] 채팅 리스트 리사이즈 함수 제거

---

Backend/src/categories/categories.service.ts
Backend/src/categories/dto/categories.dto.ts
Backend/src/categories/dto/category.dto.ts
Backend/src/lives/lives.service.ts

카테고리 api 시청자 수, 방송 수 추가를 구현했습니다. 원래 redis 를 활용한 캐시 전략을 적용해 보려고 했지만, 캐시의 키가 Redis에서 만료될 때, 에러가 나와서 철회했습니다. typeORM 에서 지원하는 캐시 기능도 오히려 응답 속도가 느려서 단순하게 집계 쿼리로 구현했습니다.

[Feature] 카테고리 api 시청자 수, 방송 수 추가

---

Backend/src/auth/auth.controller.spec.ts
Backend/src/auth/auth.service.spec.ts
Backend/src/auth/auth.service.ts
Backend/src/categories/categories.controller.spec.ts
Backend/src/categories/categories.service.spec.ts
Backend/src/follow/follow.controller.spec.ts
Backend/src/follow/follow.service.spec.ts
Backend/src/users/users.controller.spec.ts
Backend/src/users/users.service.spec.ts

users, follow 모듈의 테스트 코드를 새로 작성했습니다. auth 는 기존 코드를 리팩토링했습니다. categories 테스트 코드에 viewerCount, liveCount 업데이트 했습니다.
```
Test Suites: 4 failed, 11 passed, 15 total
Tests:       1 failed, 58 passed, 59 total
Snapshots:   0 total
Time:        39.4 s, estimated 51 s
Ran all test suites.
```
- `lives`, `chats` 모듈의 테스트 코드만 작성하면 테스트 커버리지가 100% 로 될 거 같습니다.
- Refactor
- Create
- Update

[Test] auth, users, follow, categories 테스트 코드 수정

---

Backend/apps/api/src/follow/follow.controller.ts
Backend/apps/api/src/follow/follow.service.ts
Backend/apps/api/src/users/entity/user.entity.ts

- **엔드포인트:** `GET /follow/count/streamerId`
- **설명:** 스트리머의 수 확인
- **인증:** 필요
- **파라미터:**
- **경로:**
- `streamerId` (정수, 필수): 스트리머의 ID.
- **응답:**
- **성공 (200):** 확인 메시지.
- **오류 (400/500):**
```
{
"streamerId": 1,
"followerCount": 1
}
```

[Feature] 스트리머 팔로우 수 조회 API

---

Backend/apps/api/src/lives/lives.controller.ts
Backend/apps/api/src/lives/lives.service.ts
Backend/server/encoding/cleanup.sh
Backend/server/encoding/nginx.conf
Backend/server/encoding/stream_process.sh

기존에는 연결이 끊어지면 ffmpeg이 종료가 끊어지는 것을 이용해 cleanup 스크립트를 호출하였으나 publish_done 이벤트에서 cleanup 스크립트를 5초 후에 실행 시키는 것으로 변경하였습니다.
- stream_process 스크립트에서 cleanup 스크립트 호출하지 않게 수정
- publish_done 이벤트에서 cleanup 스크립트 호출하도록 변경
- DELETE /onair/:streamingKey api 경로 변수 잘못 들어가 있던 것 수정
- closes #272

[Config] 방송 송출 종료 5초 후 방종 처리되도록 스크립트 변경

---

Backend/apps/api/src/chats/chats.controller.ts
Backend/apps/api/src/chats/chats.service.ts
Backend/apps/chats/src/chats.gateway.ts

채팅 입력 시 메시지를 소켓으로 전송한 후 인공지능 채팅 필터의 결과가 도착하면 별도의 이벤트를 발행하여 브라우저에서 후처리가 가능하도록 변경하였습니다.
- 채팅 입력 시 채팅 필터링 결과 별도 전달
- 기존 채팅 내역 저장은 채팅 필터링 결과를 포함하여 한번에 저장
- AI 채팅 필터 파라미터값 변경
https://github.com/user-attachments/assets/ff4c2d9a-8aef-4414-8dce-cf8758f1b2ce

[Fix] 채팅 필터 적용에 따른 지연 문제 수정

---

Backend/apps/api/src/app.module.ts
Backend/apps/api/src/common/filters/http-exception.filter.ts
Backend/apps/api/src/common/interceptors/logging.interceptor.ts
Backend/apps/api/src/config/logger.config.ts
Backend/apps/api/src/follow/follow.service.ts
Backend/package-lock.json
Backend/package.json

처음에는 Winston을 활용하여 파일 하나 하나에 this.logger 를 붙이다가 이건 아니다 싶어서 찾아보니 글로벌 로깅 인터셉터와 예외 필터를 적용할 수 있더라구요. 그래서 방향을 바꿨습니다. API 서버 한정이긴 하지만 애플리케이션의 로깅 관리가 전역적으로 될 것입니다. 에러 발생 시 보다 효과적인 대응이 가능해졌습니다. 
만약 `logLevel` 이나 `logDir` 를 변경하고 싶으면 `logger.config.ts` 에서 관리하면 될 거 같습니다.
```
const logLevel = 'warn';
const logDir = './logs';
```
또한, 팔로우 서비스에서 시청자 수(viewers)를 반환하도록 수정했습니다.
사진 대신에 예시
```
2024-11-26T12:58:54.129Z [ERROR]: HTTP Status: 404 Error Message: {"message":"Cannot PUT /lives","error":"Not Found","statusCode":404}
2024-11-26T12:59:11.807Z [WARN]: Unauthorized access attempt: GET /follow
2024-11-26T12:59:11.808Z [ERROR]: HTTP Status: 401 Error Message: {"message":"Unauthorized","error":"Unauthorized","statusCode":401}
```

[Feature] 로깅 인터셉터와 필터 적용

---

Frontend/src/components/chat/ChatHeader.tsx
Frontend/src/components/chat/ChatMessage.tsx
Frontend/src/components/chat/ChatSettingsMenu.tsx
Frontend/src/components/chat/ChatWindow.tsx
Frontend/src/components/common/Toggle/index.tsx
Frontend/src/types/live.ts

- 채팅 클린봇 모드를 구현했습니다.
- 채팅 헤더의 더보기 버튼을 통해 클린봇, 채팅 팝업 버튼에 접근할 수 있습니다.
- 클린 봇 모드는 토글 버튼을 통해 on/off를 할 수 있습니다.
- 공용 토글 버튼을 구현했습니다.
- closes #이슈번호

[Feature] 채팅 클린봇 모드 구현

---

Backend/apps/chats/src/chats.gateway.ts

redis mulit 사용하면서 결과를 이중배열로 받게 되었으나 해당 부분 고려하지 않아 응답이 2중배열로 반환되었음
- oldchats를 기존과 동일하게 배열로 반환하도록 수정

[Fix] oldchats가 2중배열로 전달되는 문제 수정

---

Backend/server/encoding/stream_process.sh

rw_timeout을 2배로 증가 시켜 송출 시작 시 프로토콜 변환에 의해 발생하는 지연에 의해 송출 실패가 발생하는 경우가 감소하도록 하였습니다.
오브젝트 스토리지 마운트 서드파티 툴을 rclone을 변경하였습니다.
네트워크 부하를 줄이기 위해 delete_segments 옵션을 제거하였습니다.
rclone 마운트 옵션
rclone mount ncp:lico /lico/rclone \
--vfs-cache-mode full \
--vfs-cache-max-size 2G \
--vfs-cache-max-age 5m \
--vfs-write-back 1s \
--buffer-size 32M \
--attr-timeout 1s \
--dir-cache-time 1s \
--transfers 10 \
--checkers 10 \
--allow-other \
--daemon
- rw_timeout 20초로 증가
- 오브젝트 스토리지 마운트 도구 rclone으로 변경
- 파일 저장 경로 rclone 마운트 디렉토리로 변경
- delete_segments 옵션 제거

[Fix]: 인코딩 옵션 조정(웹 스튜디오 송출 불가 문제 수정, 저장 경로 rclone마운트 디렉토리 로 변경)

---

Backend/apps/api/src/auth/auth.controller.ts
Backend/apps/api/src/auth/auth.module.ts
Backend/apps/api/src/auth/auth.service.ts
Backend/apps/api/src/auth/strategies/jwt.strategy.ts
Backend/apps/api/src/auth/strategies/lico.strategy.ts
Backend/apps/api/src/users/entity/user.entity.ts
Backend/package-lock.json
Backend/package.json

- `/auth/lico/callback` 엔드포인트를 추가하여 우리 서비스인 lico의 간단한 회원가입 및 로그인 기능을 구현하였습니다.
-   [api 문서 참고](https://far-woodwind-e60.notion.site/auth-provider-callback-c3110eda21fe4a25a826614c09981917?pvs=4)
- 이를 위해 `passport-custom` 모듈을 설치하고, LicoStrategy를 생성하여 기존의 OAuth 전략과 통합하였습니다.
- **passport-custom**은 Passport.js에서 커스텀 인증 전략을 구현할 수 있게 해주는 모듈입니다.
- NestJS에서 기본 제공되는 인증 전략 외에, 특정 요구사항에 맞는 커스텀 인증 로직을 구현해야 할 때 **passport-custom**을 사용하는 것이 권장됩니다.
- LicoStrategy는 요청 시 랜덤한 사용자 ID를 생성하고, 회원가입과 로그인을 동시에 처리합니다.
- 구조 상 그냥 db에 정보가 생성됩니다. 그리고 매번 요청하면 무한 생성되는 문제가 있습니다.
- `/auth/lico/callback` 엔드포인트 추가 및 관련 로직 구현
-  passport-custom 모듈 설치 및 LicoStrategy 생성
- AuthModule, AuthController에 LicoStrategy 등록 및 적용
- UserEntity의 oauthPlatform에 'lico' 옵션 추가
- 기존 코드와의 통합 및 엔드포인트 일관성 유지
users 테이블
lives 테이블

[Feature] : 가계정 기능 구현

---

Backend/apps/api/src/chats/chats.service.ts
Backend/apps/api/src/lives/lives.controller.ts
Backend/apps/api/src/lives/lives.service.ts

웹스튜디오로 WHIP 요청을 보내기 전에 방송이 진행중인지 여부를 체크할 수 있도록 방송 진행상태 획득 API 추가
방송 시작 시 시청자 수 초기화 추가, multi로 채팅 초기화와 연속적으로 수행되도록 변경
- GET /lives/onair/:streamingKey 방송 진행 상태 획득 API 추가
- 방송 시작 시 시청자 수 초기화

[Fix] 방송 진행 중 여부 획득 API 추가 및 방송 시작 시 viewers 초기화 하도록 변경

---

Frontend/src/apis/follow.ts
Frontend/src/components/category/CategoryCard/index.tsx
Frontend/src/hooks/useFollow.ts
Frontend/src/pages/CategoryPage/index.tsx
Frontend/src/pages/FollowingPage/index.tsx
Frontend/src/pages/LivePage/LiveInfo.tsx
Frontend/src/pages/LivePage/StreamerInfo.tsx
Frontend/src/pages/LivePage/index.tsx
Frontend/src/pages/StudioPage/StreamInfo.tsx
Frontend/src/types/category.ts

- 라이브 페이지 스트리머 정보란에 팔로워 수가 표시됩니다.
- 카테고리 페이지의 카테고리 별 시청자 수와 라이브 방송 개수가 표시됩니다.
- 팔로우 페이지 채널 카드의 시청자 수가 표시됩니다.
- closes #이슈번호

[Feature] 팔로워 수, 카테고리 페이지 라이브와 시청자 수 api 연결

---

Backend/apps/api/src/auth/strategies/lico.strategy.ts

가계정(`auth/lico/guest`) 로 임시 계정 생성 시 프로필이 `null` 이였습니다. 가계정도 profile 이미지를 더미로 넣어달라는 요청이 있었습니다. 일단은, 개발 편의상 저희 lico 아이콘 하나만 추가합니다. 
오늘 이것도 여러 개의 랜덤 이미지로 프로필이 생성되도록 구현하겠습니다.

[Feature] 가계정 임시 프로필 설정

---

Backend/apps/api/src/auth/strategies/lico.strategy.ts
Backend/apps/api/src/lives/entity/live.entity.ts

가계정으로 로그인 및 회원가입을 시도하면 임시 프로필 이미지를 생성합니다. 저희 lico 아이콘에서 색깔만 다른 것을 30개 만들었습니다(ppt 활용). 0~30 의 랜덤값을 받아서 기본 프로필 이미지로 사용합니다.
개발 일지 작성하는 김에 집계 쿼리로 속도 개선한 내용을 작성하고 있었습니다. 여러가지 시도했는데 결론이 index 여서 추가합니다.

[Feature] 가계정  프로필 이미지 랜덤 생성
